---
title: "A novel combinatorial panel for flow cytometry-based isolation of enteric nervous system cells from human intestine "
output: html_document
---

##      Loading libraries
```{r, echo = F}
library("Seurat")
library("dplyr")
library("ggplot2")
library("cowplot")
library("reticulate")
library("patchwork")
library("tidyverse")
library("RColorBrewer")
library("viridis")
library("scCustomize")
```

##      Loading dissociation score markers and others
```{r, echo = FALSE}
genes.dissoc <- c("ATF3", "BTG2", "CEBPB", "CEBPD", "CXCL3", "CXCL2", "CXCL1", "DNAJA1", "DNAJB1", "DUSP1", "EGR1", "FOS", "FOSB", "HSP90AA1", "HSP90AB1", "HSPA1A", "HSPA1B", "HSPA1A", "HSPA1B", "HSPA8", "HSPB1", "HSPE1", "HSPH1", "ID3", "IER2", "JUN", "JUNB", "JUND", "MT1X", "NFKBIA", "NR4A1", "PPP1R15A", "SOCS3", "ZFP36", "GADD45B", "IER3")
```
##    Pre-processing single datasets
##      ⊢Pre-processing Ileum_1
```{r}
Matrix_Ileum_1 <- Read10X(data.dir= "Ileum1/")
Ileum_1 <- CreateSeuratObject(counts = Matrix_Ileum_1)
Ileum_1$sample <- "Ileum_1"
Ileum_1[["percent.mt"]] <- PercentageFeatureSet(Ileum_1, pattern = "^MT-")
Ileum_1[["percent.ribo"]] <- PercentageFeatureSet(Ileum_1, pattern =  "^RP")
VlnPlot(Ileum_1, features = c("nFeature_RNA", "nCount_RNA", "percent.mt","percent.ribo"), ncol = 2)
```

```{r}
Ileum_1 <- subset(Ileum_1, subset = nFeature_RNA > 200 & nFeature_RNA < 6000 & percent.mt < 25 & percent.ribo < 30 
                  & nCount_RNA < 20000)
```

```{r, echo=FALSE}
Ileum_1 <- NormalizeData(Ileum_1)
Ileum_1 <- AddModuleScore(Ileum_1, features = list(genes.dissoc), ctrl.size = 20, name = "genes_dissoc")
Ileum_1 <- FindVariableFeatures(Ileum_1, selection.method = "vst", nfeatures = 2000)
Ileum_1 <- ScaleData(Ileum_1,vars.to.regress = c("percent.mt", "genes_dissoc1"))
Ileum_1 <- RunPCA(Ileum_1, features = VariableFeatures(object = Ileum_1))
Ileum_1 <- FindNeighbors(Ileum_1, dims = c(1:20))
Ileum_1 <- FindClusters(Ileum_1, resolution = 0.6)
Ileum_1 <- RunUMAP(Ileum_1, dims = 1:20)
DimPlot(Ileum_1, reduction = "umap", label = T, pt.size = 1)
```

##      ⊢Pre-processing Ileum_2
```{r}
Matrix_Ileum_2 <- Read10X(data.dir= "Ileum2/")
Ileum_2 <- CreateSeuratObject(counts = Matrix_Ileum_2)
Ileum_2$sample <- "Ileum_2"
Ileum_2[["percent.mt"]] <- PercentageFeatureSet(Ileum_2, pattern = "^MT-")
Ileum_2[["percent.ribo"]] <- PercentageFeatureSet(Ileum_2, pattern =  "^RP")
VlnPlot(Ileum_2, features = c("nFeature_RNA", "nCount_RNA", "percent.mt","percent.ribo"), ncol = 2)
```

```{r}
Ileum_2 <- subset(Ileum_2, subset = nFeature_RNA > 200 & nFeature_RNA < 6000 & percent.mt < 25 & percent.ribo < 30 
                  & nCount_RNA < 30000)
```

```{r, echo=FALSE}
Ileum_2 <- NormalizeData(Ileum_2)
Ileum_2 <- AddModuleScore(Ileum_2, features = list(genes.dissoc), ctrl.size = 20, name = "genes_dissoc")
Ileum_2 <- FindVariableFeatures(Ileum_2, selection.method = "vst", nfeatures = 2000)
Ileum_2 <- ScaleData(Ileum_2,vars.to.regress = c("percent.mt", "genes_dissoc1"))
Ileum_2 <- RunPCA(Ileum_2, features = VariableFeatures(object = Ileum_2))
Ileum_2 <- FindNeighbors(Ileum_2, dims = c(1:20))
Ileum_2 <- FindClusters(Ileum_2, resolution = 0.6)
Ileum_2 <- RunUMAP(Ileum_2, dims = 1:20)
DimPlot(Ileum_2, reduction = "umap", label = T, pt.size = 1)
```


##      ⊢Pre-processing Colon_1
```{r}
Matrix_Colon_1 <- Read10X(data.dir= "Colon1/")
Colon_1 <- CreateSeuratObject(counts = Matrix_Colon_1)
Colon_1$sample <- "Colon_1"
Colon_1[["percent.mt"]] <- PercentageFeatureSet(Colon_1, pattern = "^MT-")
Colon_1[["percent.ribo"]] <- PercentageFeatureSet(Colon_1, pattern =  "^RP")
VlnPlot(Colon_1, features = c("nFeature_RNA", "nCount_RNA", "percent.mt","percent.ribo"), ncol = 2)
```

```{r}
Colon_1 <- subset(Colon_1, subset = nFeature_RNA > 200 & nFeature_RNA < 6000 & percent.mt < 25 & percent.ribo < 30 
                  & nCount_RNA < 30000)
```

```{r}
Colon_1 <- NormalizeData(Colon_1)
Colon_1 <- AddModuleScore(Colon_1, features = list(genes.dissoc), ctrl.size = 20, name = "genes_dissoc")
Colon_1 <- FindVariableFeatures(Colon_1, selection.method = "vst", nfeatures = 2000)
Colon_1 <- ScaleData(Colon_1,vars.to.regress = c("percent.mt", "genes_dissoc1"))
Colon_1 <- RunPCA(Colon_1, features = VariableFeatures(object = Colon_1))
Colon_1 <- FindNeighbors(Colon_1, dims = c(1:20))
Colon_1 <- FindClusters(Colon_1, resolution = 0.6)
Colon_1 <- RunUMAP(Colon_1, dims = 1:20)
DimPlot(Colon_1, reduction = "umap", label = T, pt.size = 1)
```

##      ⊢Pre-processing Colon_2
```{r}
Matrix_Colon_2 <- Read10X(data.dir= "Colon2/")
Colon_2  <- CreateSeuratObject(counts = Matrix_Colon_2)
Colon_2$sample <- "Colon_2"
Colon_2[["percent.mt"]] <- PercentageFeatureSet(Colon_2, pattern = "^MT-")
Colon_2[["percent.ribo"]] <- PercentageFeatureSet(Colon_2, pattern =  "^RP")
VlnPlot(Colon_2, features = c("nFeature_RNA", "nCount_RNA", "percent.mt","percent.ribo"), ncol = 2)
```

```{r}
Colon_2 <- subset(Colon_2, subset = nFeature_RNA > 200 & nFeature_RNA < 6000 & percent.mt < 25 & percent.ribo < 30 
                  & nCount_RNA < 30000)
```

```{r}
Colon_2 <- NormalizeData(Colon_2)
Colon_2 <- AddModuleScore(Colon_2, features = list(genes.dissoc), ctrl.size = 20, name = "genes_dissoc")
Colon_2 <- FindVariableFeatures(Colon_2, selection.method = "vst", nfeatures = 2000)
Colon_2 <- ScaleData(Colon_2,vars.to.regress = c("percent.mt", "genes_dissoc1"))
Colon_2 <- RunPCA(Colon_2, features = VariableFeatures(object = Colon_1))
Colon_2 <- FindNeighbors(Colon_2, dims = c(1:20))
Colon_2 <- FindClusters(Colon_2, resolution = 0.6)
Colon_2 <- RunUMAP(Colon_2, dims = 1:20)
DimPlot(Colon_2, reduction = "umap", label = T, pt.size = 1)
```

##      Integration of Ileum and Colon 
```{r}
IleumAndColon.list <- c(Ileum_1, Ileum_2, Colon_1, Colon_2)
IleumAndColon.list <- lapply(X = IleumAndColon.list, FUN = function(x) {
    x <- NormalizeData(x)
    x <- FindVariableFeatures(x, selection.method = "vst", nfeatures = 2000)
})
features <- SelectIntegrationFeatures(object.list = IleumAndColon.list)
```

````{r}
Data.anchors <- FindIntegrationAnchors(object.list = IleumAndColon.list, anchor.features = features)
Data.combined <- IntegrateData(anchorset = Data.anchors)
# backup Data.combined in unaltered state
Data.combined.backup <- Data.combined
```

##      Integrated analysis of Ileum and Colon
```{r}
# it was necessary to regress out dissociation score again
DefaultAssay(Data.combined) <- "integrated"
Data.combined <- ScaleData(Data.combined, verbose = FALSE)
Data.combined <- RunPCA(Data.combined, npcs = 20, verbose = FALSE)
Data.combined <- RunUMAP(Data.combined, reduction = "pca", dims = 1:20)
Data.combined <- FindNeighbors(Data.combined, reduction = "pca", dims = 1:20)
Data.combined <- FindClusters(Data.combined, resolution = 0.6)
```

```{r}
DimPlot(Data.combined, label = TRUE, pt.size = 0.5) + NoLegend()
DimPlot(Data.combined, label = FALSE, pt.size = 0.1, cols = c('1' = 'darkorange3', '2' = 'firebrick3', '3' = 'deeppink4',
                                                             '4' = 'chartreuse4', '5' = 'cornflowerblue',
                                                             '6' = 'firebrick3', '7' = 'burlywood4')) + NoLegend()
DimPlot(Data.combined, label = TRUE, pt.size = 1, group.by = "sample")
```

##        ⊢Renaming clusters
```{r}
DefaultAssay(Data.combined) <- "RNA"
new.cluster.ids <- c("1", "1", "1", "1", "1", "1", "1", "1", "2", "1", "3", "4", "5", "1", "6", "7")
names(new.cluster.ids) <- levels(Data.combined)
Data.combined <- RenameIdents(Data.combined, new.cluster.ids)
```

##       ⊢Finding cluster markers
```{r}
Data.combined_markers <- FindAllMarkers(Data.combined, only.pos = TRUE, min.pct = 0.25, logfc.threshold = 0.25)
Data.combined_markers$delta <- Data.combined_markers$pct.1 - Data.combined_markers$pct.2
```

##      ⊢Subset neurons
```{r}
neurons <- subset(Data.combined, idents = 4)
DefaultAssay(neurons) <- "integrated"
neurons <- AddModuleScore(neurons, features = list(genes.dissoc), ctrl.size = 20, name = "genes_dissoc")
neurons <- ScaleData(neurons, vars.to.regress = "genes_dissoc1", verbose = FALSE)
neurons <- RunPCA(neurons, npcs = 20, verbose = FALSE)
ElbowPlot(neurons, reduction = "pca")
neurons <- RunUMAP(neurons, reduction = "pca", dims = 1:10)
neurons <- FindNeighbors(neurons, reduction = "pca", dims = 1:10)
neurons <- FindClusters(neurons, resolution = 0.5)
neurons <- RunUMAP(neurons, dims = c(1:10))
DimPlot(neurons, reduction = "umap", label = F, pt.size = 1)
DefaultAssay(neurons) <- "RNA"
neurons_markers <- FindAllMarkers(neurons, only.pos = TRUE, min.pct = 0.25, logfc.threshold = 0.25)
neurons_markers$delta <- neurons_markers$pct.1 - neurons_markers$pct.2
```

